version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["./entrypoint.sh"]  # Entrypoint script includes ["python3 manage.py runserver"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data using a named volume
    ports:
      - "3306:3306"

volumes:
  mysql_data:  # Named volume for MySQL data persistence across container restarts